// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA89zAANvuNFUSLr46yWCYvSsIEGOxbodM',
    appId: '1:1056741315126:web:e380cb565d9bd5b152be97',
    messagingSenderId: '1056741315126',
    projectId: 'bwashamo-f98ff',
    authDomain: 'bwashamo-f98ff.firebaseapp.com',
    storageBucket: 'bwashamo-f98ff.appspot.com',
    measurementId: 'G-9BCB1X30MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD81MMNbMOs1v45lzop7mJHsxdsZm3rSjY',
    appId: '1:1056741315126:android:4a62038f4dbf96f252be97',
    messagingSenderId: '1056741315126',
    projectId: 'bwashamo-f98ff',
    storageBucket: 'bwashamo-f98ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa7BWIGHjtv_QLWbWxdoVPf66RFcHaOvI',
    appId: '1:1056741315126:ios:8911593357ab53c952be97',
    messagingSenderId: '1056741315126',
    projectId: 'bwashamo-f98ff',
    storageBucket: 'bwashamo-f98ff.appspot.com',
    iosClientId:
        '1056741315126-qr8geqkc90u8bk5sascj76mjtgmf3br3.apps.googleusercontent.com',
    iosBundleId: 'com.example.shamo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa7BWIGHjtv_QLWbWxdoVPf66RFcHaOvI',
    appId: '1:1056741315126:ios:8911593357ab53c952be97',
    messagingSenderId: '1056741315126',
    projectId: 'bwashamo-f98ff',
    storageBucket: 'bwashamo-f98ff.appspot.com',
    iosClientId:
        '1056741315126-qr8geqkc90u8bk5sascj76mjtgmf3br3.apps.googleusercontent.com',
    iosBundleId: 'com.example.shamo',
  );
}
